apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: akk-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: default
  source:
    repoURL: https://github.com/akkercheval/akk-gitops.git
    targetRevision: main
    path: secrets/sealedsecrets
  destination:
    server: https://kubernetes.default.svc
    namespace: akk-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      # Ignore the README.md; only apply YAML SealedSecret manifests.
      - CreateNamespace=true
