apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared-akk
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: default
  source:
    repoURL: https://github.com/akkercheval/akk-gitops.git
    targetRevision: main
    path: infra/cloudflared
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflared
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
