---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-akk-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgC3Cn35NmhRVQRG9eMJQ/LzCl/5RsPr+9rYNxzQQzrpzx1jO2w523eK6bX91xMoxBv4+uL4lwhMliW6IzX2dKVSNWeNwhLY6Iq2mY9PifXabp4JkIgfp7Iu0pucbY4v/Hv2VYMWCyY0xTWCtw9ZE+AyQsgEktANavzEngo6q1TSQNUBFhw6CHe8988coV2emxgnY5LCP+15JXkjD6xGKj5iQ1vpzWU+5Eho3edhNzRLpzQFIzD3rPX9SCaIc80HylHRkRqzCWclmqloyVo2vq9TkVe0M42OmU1hqEaiIkQ56wUHlVQRHi46iIVGTSRxamSj4INyM5YeVcB8cJ9HF2/egRp6BrchrZMQ5ITyZjc0XAF1BFvqPecS0jZGJOZ4dQ8/4XhYAdHvN29cDVqScHV4rzSN3OYrYMnd7f3emrudRDtIbIDISKoZGvGTUQmZbEGDpQYM3uPszMKmJbJkv3tkh05Rd7caJU/K4hWlJyZO6qP7PK4bQS9GF9EeKGlVooKL5Ut1QIpdQhB1yi5BRHGQFI4ScFlymk16ct6rAFgYPf0GtNZ0RiNWiGwNeTjj9h8yN2YRXlBViyuDJZph2y5qRpVWkuAtnzH7pgUnMP4xnEdobd5QI+qJ5sRlsyhmlRd4gbAoEUH/yGhaVYbfOUWR9/9HE8Xk4p8UDdB/Pk65/8mj/ajDaRHaXAOMhu77nE4iGXF8jNRmE7G/wyo69xLR9XZdPty0FRGM7PDlWv64StltTRVmIGjzeuc+fjlLDkZGP1EakIgIsLHS/viK2+IrADjR+06ofdk3h934+RGwhPnLEq29sf/vZHBuTbMPplhSE1G2tuBQZGdcuruAN2LB3hOjC1BvmIO2YiTXgOqJuhZwZHLdltwhu4Mkgc2gHMCiT+SI4KHt3KAFFLlbIoFbFf2OepYL+Fu9oE0Adxr3NQQr6Y1WFL4I
  template:
    metadata:
      name: cloudflared-akk-token
      namespace: cloudflared
