apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-akk
  namespace: cloudflared
  labels:
    app: cloudflared-akk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared-akk
  template:
    metadata:
      labels:
        app: cloudflared-akk
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          args:
            - tunnel
            - --no-autoupdate
            - run
            - --token
            - $(CLOUDFLARE_TOKEN)
          env:
            - name: CLOUDFLARE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflared-akk-token
                  key: token
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
